<div id="dialog-confirm" title="Deseja realmente excluir este registro?">
</div>
<section class="content-header">
    <h1>
        Galeria de Fotos
        <small>Vejá e Publique novas Fotos</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="/admin/galeria-de-fotos/publicar">Publicar novas Fotos</a></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->form()->openTag($form); ?> 
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('imagem')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 pull-right">
                    <?php echo $this->formRow($form->get('salvar')); ?> 
                </div>
            </div>
            <?php echo $this->form()->closeTag($form); ?> 

            <h1>
                <small>Vejá as fotos publicadas neste álbum</small>
            </h1>    
            <div class="row" style="padding-top: 25px;">
                <?php foreach ($fotos as $img): ?>
                    <div class="col-md-2 portfolio-item" data-referencia="<?= $img['id']; ?>">
                        <a href="<?php echo $img['imagem'] . "." . $img['extensao']; ?>" >
                            <img width="140px" height="104px;"  src="<?php echo $img['imagem'] . "." . $img['extensao']; ?>" alt="">
                        </a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ação <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" class="excluir-foto" id="<?= $img['id']; ?>" >Excluir Registro</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php endforeach; ?>

            </div>

        </div>
    </div>
</section>
<style>
    .portfolio-item {
        margin-bottom: 25px;
    }
    .caret-up {
        width: 0; 
        height: 0; 
        border-left: 4px solid rgba(0, 0, 0, 0);
        border-right: 4px solid rgba(0, 0, 0, 0);
        border-bottom: 4px solid;

        display: inline-block;
        margin-left: 2px;
        vertical-align: middle;
    }
</style>
<script>
    $(function () {
        $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).fadeIn("fast");
                    $(this).toggleClass('open');
                    $('b', this).toggleClass("caret caret-up");
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).fadeOut("fast");
                    $(this).toggleClass('open');
                    $('b', this).toggleClass("caret caret-up");
                });
    });
</script>