<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>CONTATO</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Contato
        </div>
    </div>

    <div class="eng_background_int">

        <div class="contato">
            <h4>Entre em contato com a gente</h4>
            <div role="form" class="wpcf7" id="wpcf7-f4-o1" lang="pt-BR" dir="ltr">
                <div class="screen-reader-response"></div>
                <form name="" action="http://ctgespelhodatradicao.com.br/contato/#wpcf7-f4-o1" method="post" class="wpcf7-form" novalidate="novalidate">
                    <div style="display: none;">
                        <input type="hidden" name="_wpcf7" value="4" />
                        <input type="hidden" name="_wpcf7_version" value="4.1.2" />
                        <input type="hidden" name="_wpcf7_locale" value="pt_BR" />
                        <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4-o1" />
                        <input type="hidden" name="_wpnonce" value="92eee19fa7" />
                    </div>
                    <p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="Nome*:" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required large_cont" aria-required="true" aria-invalid="false" /></span><br />
                        <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="Email*:" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email large_cont" aria-required="true" aria-invalid="false" /></span><br />
                        <span class="wpcf7-form-control-wrap your-cidade"><input type="text" name="your-cidade" value="Cidade:" size="40" class="wpcf7-form-control wpcf7-text small_cont" aria-invalid="false" /></span><br />
                        <span class="wpcf7-form-control-wrap your-telefone"><input type="text" name="your-telefone" value="Telefone:" size="40" class="wpcf7-form-control wpcf7-text small_cont" aria-invalid="false" /></span><br />
                        <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false">Mensagem*:</textarea></span><br />
                        <input type="submit" value="Enviar" class="wpcf7-form-control wpcf7-submit submit" /></p>
                    <div class="wpcf7-response-output wpcf7-display-none"></div></form></div>    
        </div>

        <div class="info_contato">
            <div class="endereco_contato">
                CTG Potro Sem Dono<br>
                Rua João Moreira Filho, S/N - Centro, Guatambu-SC<br/>
                <a href="mailto:contato@ctgpotrosemdono.com.br">contato@ctgpotrosemdono.com.br</a>
            </div>
            <div class="tel_contato">
                <span>(49)</span> 3336.0034
            </div>
        </div>

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12429.92471484326!2d-52.78313889999924!3d-27.133110502546327!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjfCsDA3JzU5LjIiUyA1MsKwNDYnNTkuMyJX!5e1!3m2!1spt-BR!2sbr!4v1443137245096" width="100%;" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>