<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>CONTATO</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Contato
        </div>
    </div>

    <div class="eng_background_int">
        <div class="contato">
            <h4>Entre em contato com a gente</h4>
            <div role="form" class="wpcf7" id="wpcf7-f4-o1" lang="pt-BR" dir="ltr">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formRow($form->get('nome')); ?>
                <?php echo $this->formRow($form->get('email')); ?>
                <?php echo $this->formRow($form->get('cidade')); ?>
                <?php echo $this->formRow($form->get('telefone')); ?>
                <?php echo $this->formRow($form->get('mensagem')); ?>
                <?php echo $this->formRow($form->get('enviar')); ?>
                <?php echo $this->form()->closeTag($form); ?>
            </div>    
        </div>

        <div class="info_contato">
            <div class="endereco_contato">
                CTG Potro Sem Dono<br>
                Rua João Moreira Filho, S/N - Centro, Guatambu-SC<br/>
                <a href="mailto:contato@ctgpotrosemdono.com.br">contato@ctgpotrosemdono.com.br</a>
            </div>
            <div class="tel_contato">
                <span>(49)</span> 3336.0034
            </div>
        </div>
        
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12429.92471484326!2d-52.78313889999924!3d-27.133110502546327!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjfCsDA3JzU5LjIiUyA1MsKwNDYnNTkuMyJX!5e1!3m2!1spt-BR!2sbr!4v1443137245096" width="100%;" height="300" frameborder="0" style="border:0; margin-top: 10px;" allowfullscreen></iframe>

    </div>
</div>