<section class="content-header">
    <h1>
        Integrações
        <small>Acompanhe aqui todas as suas integrações</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/main"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="/main/integracoes">Integrações</a></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <table class="table table-striped custab" id="table-produtos">
                        <thead>
                            <a href="/main/integracoes/nova" class="btn btn-primary btn-xs pull-left"><b>+</b> Add nova Integração</a>
                            <tr><th>ID</th>
                                <th>Title</th>
                                <th>Parent ID</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tr>
                            <td>1</td>
                            <td>News</td>
                            <td>News Cate</td>
                            <td><span class="badge bg-green-gradient">Aprovado</span></td>
                            <td class="text-right">
                                <!--                                <a class='btn btn-info btn-xs' href="#">
                                                                    <span class="glyphicon glyphicon-edit" title="Editar"></span>
                                                                </a> 
                                                                <a href="#" class="btn btn-danger btn-xs">
                                                                    <span class="glyphicon glyphicon-remove" title="Deletar"></span>
                                                                </a>-->
                                <a href="#" class="btn btn-warning btn-xs">
                                    <span class="glyphicon glyphicon-inbox" title="Deletar"></span>
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
