<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>GALERIA DE FOTOS</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Galeria de Fotos
        </div>
    </div>

    <div class="eng_background_int">

        <div class="galerias">
            <div class="item_galeria">
                <a href="../galeria/desfile-7-de-setembro-2015/index.html" class="title_galeria">Desfile 7 de setembro (2015)</a>
                <a href="../galeria/desfile-7-de-setembro-2015/index.html" title="Desfile 7 de setembro (2015)" class="img_galeria"><img src="../wp-content/uploads/2015/09/11988485_1173272039355379_3265915780916207525_n-307x199.jpg" alt="Desfile 7 de setembro (2015)"/></a>
            </div>
            <div class="item_galeria">
                <a href="../galeria/xxiv-rodeio-crioulo-interestadual/index.html" class="title_galeria">XXIV Rodeio Crioulo Interestadual</a>
                <a href="../galeria/xxiv-rodeio-crioulo-interestadual/index.html" title="XXIV Rodeio Crioulo Interestadual" class="img_galeria"><img src="../wp-content/uploads/2015/02/SAM_0803-307x199.jpg" alt="XXIV Rodeio Crioulo Interestadual"/></a>
            </div>
            <div class="item_galeria">
                <a href="../galeria/frcg/index.html" class="title_galeria">FRCG</a>
                <a href="../galeria/frcg/index.html" title="FRCG" class="img_galeria"><img src="../wp-content/uploads/2014/08/2%c2%aaetapa-FRCGQuilombo2013-307x199.jpg" alt="FRCG"/></a>
            </div>
            <div class="item_galeria">
                <a href="../galeria/invernadas/index.html" class="title_galeria">Invernadas</a>
                <a href="../galeria/invernadas/index.html" title="Invernadas" class="img_galeria"><img src="../wp-content/uploads/2014/08/Envernada-Juvenil-2012-307x199.jpg" alt="Invernadas"/></a>
            </div>
            <div class="item_galeria">
                <a href="../galeria/comemoracoes-da-semana-farroupilha/index.html" class="title_galeria">Comemorações da Semana Farroupilha</a>
                <a href="../galeria/comemoracoes-da-semana-farroupilha/index.html" title="Comemorações da Semana Farroupilha" class="img_galeria"><img src="../wp-content/uploads/2014/08/Abertura-Semana-Farroupilha-20131-307x199.jpg" alt="Comemorações da Semana Farroupilha"/></a>
            </div>
            <div class="item_galeria">
                <a href="../galeria/desfiles-de-7-de-setembro/index.html" class="title_galeria">Desfiles de 7 de setembro</a>
                <a href="../galeria/desfiles-de-7-de-setembro/index.html" title="Desfiles de 7 de setembro" class="img_galeria"><img src="../wp-content/uploads/2014/08/7-de-Setembro-2013-307x199.jpg" alt="Desfiles de 7 de setembro"/></a>
            </div>
        </div>

        <div class="posts_pagination">
        </div>

    </div>
</div>