<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>GALERIA DE FOTOS</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Galeria de Fotos
        </div>
    </div>

    <div class="eng_background_int">

        <div class="galerias">
            <div class="item_galeria">
                <a href="../galeria/desfile-7-de-setembro-2015/index.html" class="title_galeria">Desfile 7 de setembro (2015)</a>
                <a href="../galeria/desfile-7-de-setembro-2015/index.html" title="Desfile 7 de setembro (2015)" class="img_galeria"><img src="../wp-content/uploads/2015/09/11988485_1173272039355379_3265915780916207525_n-307x199.jpg" alt="Desfile 7 de setembro (2015)"/></a>
            </div>
        </div>
        
        <div class="posts_pagination">
        
        </div>

    </div>
</div>