<div class="container" style="margin-top:120px">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><strong>Autenticação </strong></h3>
                <div style="float:right; font-size: 80%; position: relative; top:-10px">
                    <a href="/auth/esqueceu-sua-senha/recuperar-senha">Esqueceu sua Senha?</a>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                    <div style="margin-bottom: 12px" class="form-group">
                        <?php echo $this->formRow($form->get('email')); ?>   
                    </div>

                    <div style="margin-bottom: 12px" class="form-group">
                        <?php echo $this->formRow($form->get('senha')); ?>
                    </div>
                    
                    <?php echo $this->formRow($form->get('entrar')); ?>

                    <hr style="margin-top:10px;margin-bottom:10px;" >

                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
</div>