<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">                                
                    <div class="row-fluid user-row">
                        <img src="http://s11.postimg.org/7kzgji28v/logo_sm_2_mr_1.png" class="img-responsive" alt="Conxole Admin"/>
                    </div>

                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form); ?>  
                    <div accept-charset="UTF-8" role="form" class="form-signin">
                        <fieldset>
                            <label class="panel-login">
                                <div class="login_result"></div>
                            </label>
                            <?php echo $this->formRow($form->get('email')); ?> 
                            <?php echo $this->formRow($form->get('senha')); ?> 
                            <div class="panel-heading">
                                <div style="float:left; margin-left: -14px; position: relative; top:-10px"><a href="/app/esqueceu-sua-senha">Esqueçeu sua Senha?</a></div>
                            </div>     
                            <?php echo $this->formRow($form->get('login')); ?>     
                        </fieldset>
                    </div>
                    <?php echo $this->form()->closeTag($form); ?>  
                </div>
            </div>
        </div>
    </div>
</div>