<div class="content">
    <div class="eng_background">
        <div class="banner">
            <a class="backward"></a>
            <div class="images">
                <div class="principal">
                    <div class="text_banner">
                        <h1><a href="informativo/abertura-da-semana-farroupilha-2015/index.html" title="Abertura da Semana Farroupilha 2015">Abertura da Semana Farroupilha 2015</a></h1>
                        <p><a href="informativo/abertura-da-semana-farroupilha-2015/index.html" title="Abertura da Semana Farroupilha 2015">Abertura da Semana Farroupilha 2015</a></p>
                        <!--<p><strong>CONFIRA A PROGRAMAÇÃO</strong></p>-->
                    </div>
                    <a href="informativo/abertura-da-semana-farroupilha-2015/index.html" title="Abertura da Semana Farroupilha 2015"><img src="wp-content/uploads/2015/09/IMG_20150912_1710362741-500x362.jpg" alt="Abertura da Semana Farroupilha 2015"/></a>
                </div>
                <div class="principal">
                    <div class="text_banner">
                        <h1><a href="informativo/acampamento-farroupilha-2015/index.html" title="Acampamento Farroupilha 2015">Acampamento Farroupilha 2015</a></h1>
                        <p><a href="informativo/acampamento-farroupilha-2015/index.html" title="Acampamento Farroupilha 2015">De 12 a 20 de setembro. Confira a programação!</a></p>
                        <!--<p><strong>CONFIRA A PROGRAMAÇÃO</strong></p>-->
                    </div>
                    <a href="informativo/acampamento-farroupilha-2015/index.html" title="Acampamento Farroupilha 2015"><img src="wp-content/uploads/2015/08/banner_site_ctg.jpg" alt="Acampamento Farroupilha 2015"/></a>
                </div>
                <div class="principal">
                    <div class="text_banner">
                        <h1><a href="informativo/ctg-espelho-da-tradicao-um-motivo-de-orgulho/index.html" title="CTG Espelho da Tradição um motivo de orgulho">CTG Espelho da Tradição um motivo de orgulho</a></h1>
                        <p><a href="informativo/ctg-espelho-da-tradicao-um-motivo-de-orgulho/index.html" title="CTG Espelho da Tradição um motivo de orgulho">Conheça a nossa história de cultura, tradição e serviços ao povo de nossa terra.</a></p>
                        <!--<p><strong>CONFIRA A PROGRAMAÇÃO</strong></p>-->
                    </div>
                    <a href="informativo/ctg-espelho-da-tradicao-um-motivo-de-orgulho/index.html" title="CTG Espelho da Tradição um motivo de orgulho"><img src="wp-content/uploads/2014/08/banner1.jpg" alt="CTG Espelho da Tradição um motivo de orgulho"/></a>
                </div>
            </div><!--images-->

            <div class="transp_forward"></div>

            <a class="forward"></a>

            <div class="slidetabs">
                <a href="#"></a>
                <a href="#"></a>
                <a href="#"></a>
            </div>

        </div><!--banner-->

        <div class="content_index">

            <div class="conheca">
                <h3 class="border">CONHEÇA O CTG</h3>
                <p>Fundado em 15 de dezembro de 1987, a entidade conta hoje com centenas de associados, portanto centenas de famílias agregadas com a finalidade de cultuar a tradição gaúcha, preservando a natureza e procurando reviver os hábitos e costumes que compõem as mais gloriosas tradições do gaúcho de antanho.<br/><br/>
                    <a href="ctg/index.html" class="yellow">SAIBA MAIS</a>
                </p>
            </div>






            <div class="programacao">

                <h3 class="border">AGENDA DO MÊS</h3>

                <a class="backward2"></a>

                <div class="images2">


                    <div class="principal2">
                        <div class="text_banner">
                            Acampamento Farroupilha 2015 - <span>12/09</span>
                        </div>
                        <img src="wp-content/uploads/2015/08/banner_site_ctg-307x199.jpg" alt="Acampamento Farroupilha 2015"/>
                    </div>


                </div><!--images-->

                <a class="forward2"></a>

                <div class="slidetabs2">
                    <a href="#"></a>
                </div>

            </div>

            <div class="divisor_index"></div>

            <div class="informativo">
                <h3 class="border">INFORMATIVO</h3>

                <div class="item_informativo">
                    <div class="img_informativo">
                        <a href="informativo/patronagem-esteve-presente-na-reuniao-do-festival-2015/index.html" title="Patronagem esteve presente na Reunião do FRCG Festival 2015"><img src="wp-content/uploads/2015/02/DSC_9982-174x103.jpg" alt="Patronagem esteve presente na Reunião do FRCG Festival 2015"/></a>
                    </div>
                    <div class="info_informativo">
                        <h5><a href="informativo/patronagem-esteve-presente-na-reuniao-do-festival-2015/index.html">Patronagem esteve presente na Reunião do FRCG Festival 2015</a></h5>
                        <p><a href="informativo/patronagem-esteve-presente-na-reuniao-do-festival-2015/index.html">Reunião Festival 2015</a></p>
                    </div>
                </div>

                <div class="item_informativo">
                    <div class="img_informativo">
                        <a href="informativo/comecou-o-xxiv-rodeio-crioulo-interestadual-do-ctg-espelho-da-tradicao/index.html" title="Começou o XXIV Rodeio Crioulo Interestadual do CTG Espelho da Tradição"><img src="wp-content/uploads/2015/01/DSC_9851-174x103.jpg" alt="Começou o XXIV Rodeio Crioulo Interestadual do CTG Espelho da Tradição"/></a>
                    </div>
                    <div class="info_informativo">
                        <h5><a href="informativo/comecou-o-xxiv-rodeio-crioulo-interestadual-do-ctg-espelho-da-tradicao/index.html">Começou o XXIV Rodeio Crioulo Interestadual do CTG Espelho da Tradição</a></h5>
                        <p><a href="informativo/comecou-o-xxiv-rodeio-crioulo-interestadual-do-ctg-espelho-da-tradicao/index.html">O Lançamento do XXIV Rodeio nos mostrou quanto grande sera nosso evento.</a></p>
                    </div>
                </div>

                <div class="item_informativo">
                    <div class="img_informativo">
                        <a href="informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html" title="Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG"><img src="wp-content/uploads/2015/01/DSC_6054-174x103.jpg" alt="Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG"/></a>
                    </div>
                    <div class="info_informativo">
                        <h5><a href="informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html">Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG</a></h5>
                        <p><a href="informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html">Hoje é o grande dia do Lançamento do XXIV Rodeio Crioulo Interestadual do CTG Espelho da Tradição.</a></p>
                    </div>
                </div>
            </div><!--informativo-->

            <div class="galeria_index">
                <h3 class="border">GALERIA DE FOTOS</h3>
                <div class="eng_fotos_galeria">

                    <a href="galerias/index.html" title="Desfile 7 de setembro (2015)" class="foto_galeria_index1"><img src="wp-content/uploads/2015/09/11988485_1173272039355379_3265915780916207525_n-104x100.jpg" alt="Desfile 7 de setembro (2015)"/></a>
                    <a href="galerias/index.html" title="Desfile 7 de setembro (2015)" class="foto_galeria_index2"><img src="wp-content/uploads/2015/09/11220799_1173271932688723_3359268266237902842_n-116x99.jpg" alt="Desfile 7 de setembro (2015)"/></a>
                    <a href="galerias/index.html" title="Desfile 7 de setembro (2015)" class="foto_galeria_index3"><img src="wp-content/uploads/2015/09/11951902_1173271716022078_2088971119643329106_n-160x154.jpg" alt="Desfile 7 de setembro (2015)"/></a>
                    <a href="galerias/index.html" title="Desfile 7 de setembro (2015)" class="foto_galeria_index4"><img src="wp-content/uploads/2015/09/11214326_1173272322688684_7663011896187971764_n-226x141.jpg" alt="Desfile 7 de setembro (2015)"/></a>
                </div>
            </div>
        </div><!--content_index-->
    </div><!--eng_background-->
</div>