<div class="content">
    <div class="eng_background">
        <div class="banner">
            <a class="backward"></a>

            <div class="images">
                <div class="principal">
                    <div class="text_banner">
                        <h1><a href="informativo/abertura-da-semana-farroupilha-2015/index.html" title="Abertura da Semana Farroupilha 2015">Abertura da Semana Farroupilha 2015</a></h1>
                        <p><a href="informativo/abertura-da-semana-farroupilha-2015/index.html" title="Abertura da Semana Farroupilha 2015">Abertura da Semana Farroupilha 2015</a></p>
                        <!--<p><strong>CONFIRA A PROGRAMAÇÃO</strong></p>-->
                    </div>
                    <a href="" title="">
                        <img src="" alt=""/>
                    </a>
                </div>
            </div>

            <div class="transp_forward"></div>
            <a class="forward"></a>
            <div class="slidetabs">
                <a href="#"></a>
            </div>

        </div>

        <div class="content_index">

            <div class="conheca">
                <h3 class="border">CONHEÇA O CTG</h3>
                <p>Fundado em ...., a entidade conta hoje com centenas de associados, portanto centenas de famílias agregadas com a finalidade de cultuar a tradição gaúcha, preservando a natureza e procurando reviver os hábitos e costumes que compõem as mais gloriosas tradições do gaúcho.<br/><br/>
                    <a href="/site/o-ctg" class="yellow">SAIBA MAIS</a>
                </p>
            </div>

            <div class="programacao">
                <h3 class="border">AGENDA DO MÊS</h3>
                <a class="backward2"></a>
                
                <?php foreach ($agenda as $dado):?>
                <div class="images2">
                    <div class="principal2">
                        <div class="text_banner">
                            <?php echo $dado['evento']; ?> <span><?php echo $dado['data']->format('d-m-Y'); ?></span>
                        </div>
                        <img src="" alt=""/>
                    </div>
                </div>
                <?php endforeach; ?>
                
                <a class="forward2"></a>
            
                <div class="slidetabs2">
                    <a href="#"></a>
                </div>
            
            </div>

            <div class="divisor_index"></div>

            <div class="informativo">
                <h3 class="border">INFORMATIVO</h3>
                <?php foreach ($informativos as $item): ?>
                    <div class="item_informativo">
                        <div class="img_informativo">
                            <a href="/site/informativos/ver/id/<?php echo $item['id']; ?>" title="<?php echo $item['titulo']; ?>">
                                <img src="<?php echo $item['imagem'].".".$item['extensao']; ?>" height="103" width="174" alt="<?php echo $item['titulo']; ?>"/>
                            </a>
                        </div>
                        <div class="info_informativo">
                            <span style="font-size:11px;"><?php echo $item['cadastro']->format('d-m-Y'); ?></span>
                            <h5><a href="/site/informativos/ver/id/<?php echo $item['id']; ?>"><?php echo $item['titulo']; ?></a></h5>
                            <p><a href="/site/informativos/ver/id/<?php echo $item['id']; ?>"> <?php echo $item['descinf']; ?> </a></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="galeria_index">
                <h3 class="border">GALERIA DE FOTOS</h3>
                <div class="eng_fotos_galeria">

                </div>
            </div>
        </div>
    </div>
</div>