<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>O CTG</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; O CTG
        </div>
    </div>

    <div class="eng_background_int">
        <div class="octg">
            <p>Fundado ...., a entidade conta hoje com centenas de associados, portanto centenas de famílias agregadas com a finalidade de cultuar a tradição gaúcha, preservando a natureza e procurando reviver os hábitos e costumes que compõem as mais gloriosas tradições do gaúcho de antanho.</p>
            <p>Graças ao esforço de cada um, o CTG Potro Sem Dono forma um conjunto, que com os esforços  de seus membros,  o apoio da comunidade e da municipalidade vem prestando grandes serviços ao povo de nossa terra.</p>
            <p>No aspecto físico dispõe de uma das mais bem conservadas áreas,  localizada no parque de rodeios , composto de galpão de fandango, restaurante, churrasqueiras área de camping  e a pista de rodeios, tudo arborizado e com distribuição de água e energia elétrica.</p>
            <p>O CTG Potro Sem Dono, esta localizado com sua sede social na Rua João Moreira Filho, S/N - Centro, Guatambu-SC, onde é realizada todas as suas programações com eventos artísticos, campeiros e eventos diversos e boa culinária.</p>
        </div>

        <div class="divisor_index"></div>
        <div class="galeria_octg">
            <div id="image_wrap">
                <img src="../ctg/images/estrutura/01.jpg" width="641" height="311" />
            </div>
            <a class="prev browse left"></a>
            <div class="scrollable" id="scrollable">
                <div class="items">
                    <div>
                        <img src="../ctg/images/estrutura/01.jpg" />
                        <img src="../ctg/images/estrutura/02.jpg" />
                        <img src="../ctg/images/estrutura/03.jpg" />
                        <img src="../ctg/images/estrutura/04.jpg" />
                    </div>
                </div>
            </div>
            <a class="next browse right"></a>
        </div>

        <div class="missao">
            <h6 class="border">Patronagem</h6>
            <ul>
                <li><strong>Patrão:</strong> </li>
                <li><strong>1º Capataz:</strong> </li>
                <li><strong>2º Capataz:</strong> </li>
                <li><strong>1º Sota Capataz:</strong> </li>
                <li><strong>2º Sota Capataz:</strong> </li>
                <li><strong>1º Agregado da Guaiaca:</strong> </li>
                <li><strong>2º Agregado da Guaiaca:</strong> </li>
                <li><strong>Patrão de Honra:</strong> </li>
            </ul>
        </div>
        
    </div>
</div>