<div id="dialog-confirm" title="Deseja realmente excluir este registro?">
</div>
<section class="content-header">
    <h1>
        Informativos
        <small>Acompanhe aqui todas os seus Informativos</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/main"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="/main/integracoes">Informativos</a></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <table class="table table-striped custab" id="table-produtos">
                        <thead>

                        <div class="row">
                            <div class="col-md-6">
                                <a href="/admin/informativos/novo" class="btn btn-primary btn-sm pull-left"><b>+</b> Add novo Informativo</a>
                            </div>

                            <div class="col-md-6">
                                <div id="custom-search-input">
                                    <div class="input-group">
                                        <input type="text" class="form-control input-sm" placeholder="Buscar" />
                                        <span class="input-group-btn">
                                            <button class="btn btn-info btn-sm" type="button">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <tr>
                            <th>Título</th>
                            <th>Descrição</th>
                            <th>Texto</th>
                            <th>Data de Cadastro</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <?php foreach ($informativos as $inf): ?>
                            <tr data-referencia="<?= $inf['id']; ?>">
                                <td><?php echo $inf['titulo']; ?> </td>
                                <td><?php echo $inf['descinf']; ?> </td>
                                <td><?php echo $inf['texto']; ?></td>
                                <td><?php echo $inf['cadastro']->format('d-m-Y'); ?> </td>
                                <?php if ($inf['status'] == 1) : ?>
                                    <td>
                                        <span class="badge bg-green-gradient"><?php echo $inf['descricao']; ?> </span>
                                    </td>
                                <?php endif; ?>
                                <?php if ($inf['status'] == 2) : ?>
                                    <td>
                                        <span class="badge bg-red-gradient"><?php echo $inf['descricao']; ?> </span>
                                    </td>
                                <?php endif; ?>
                                <td>
                                    <a class="glyphicon glyphicon-edit" href="/admin/informativos/editar/id/<?php echo $inf['id']; ?>"></a>
                                    <a class="glyphicon glyphicon-trash excluir" id="<?= $inf['id']; ?>" href="#" ></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                    <div class="row col-md-6">
                        <?php
                        echo $this->paginationControl($informativos, 'Sliding', 'partials/paginator.phtml');
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        $(".excluir").click(function () {
            var id = $(this).attr('id');
            $(function () {
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 140,
                    width: 400,
                    modal: true,
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    },
                    buttons: {
                        "Sim": function () {
                            $.ajax({
                                type: 'POST',
                                url: '/admin/informativos/deletar',
                                data: {
                                    'id': id
                                },
                                success: function (response) {
                                    $('body').plainOverlay('hide');
                                    $('#dialog-confirm').dialog("close");
                                    $("[data-referencia='"+id+"']").remove();
                                },
                                beforeSend: function (xhr) {
                                    $('body').plainOverlay('show');
                                }
                            });
                        },
                        Cancelar: function () {
                            $(this).dialog("close");
                        }
                    }
                });
            });

        });
    });
</script>