<div class="container" style="margin-top:120px">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><strong>Informe seu E-mail </strong></h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                    <div style="margin-bottom: 12px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $this->formRow($form->get('email')); ?>   
                    </div>
                    <?php echo $this->formRow($form->get('recuperar')); ?>
                    <hr style="margin-top:10px;margin-bottom:10px;" >
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
</div>