<div class="content">

    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>AGENDA</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Agenda
        </div>
    </div>

    <div class="eng_background_int">
        <div class="agenda">
            
            <div class="col_left">
                <h3 class="border"> Setembro / 2015</h3>
                <div class="item_agenda">
                    <div class="img_agenda">
                        <a href="../wp-content/uploads/2015/08/banner_site_ctg.jpg" title="Acampamento Farroupilha 2015" rel="prettyPhoto[gallery]"><img src="../wp-content/uploads/2015/08/banner_site_ctg-132x85.jpg" alt="Acampamento Farroupilha 2015"/></a>
                    </div>
                    <div class="data_agenda">
                        12/09                    </div>
                    <div class="title_agenda">
                        <h4>Acampamento Farroupilha 2015</h4>
                        <p><strong>Local: </strong>CTG Espelho da Tradição<br/>
                            <strong>Horário: </strong>08:00h</p>
                    </div>
                </div>
            </div>
            
            <div class="col_right">
                <h6 class="border">PESQUISAR AGENDA</h6>
                <form class="form_agenda" name="form_agenda" method="get" action="http://ctgespelhodatradicao.com.br/pesquisa-agenda">
            
                    <select id="select_agenda_ano" title="Ano:" name="ano">
                        <option value="">ANO:</option>
                        <option value="2014">2014</option>
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                        <option value="2017">2017</option>
                        <option value="2018">2018</option>
                        <option value="2019">2019</option>
                        <option value="2020">2020</option>
                    </select>
                    
                    <select id="select_agenda_mes" title="Mês:" name="mes">
                        <option value="">MÊS:</option>
                        <option value="01">Janeiro</option>
                        <option value="02">Fevereiro</option>
                        <option value="03">Março</option>
                        <option value="04">Abril</option>
                        <option value="05">Maio</option>
                        <option value="06">Junho</option>
                        <option value="07">Julho</option>
                        <option value="08">Agosto</option>
                        <option value="09">Setembro</option>
                        <option value="10">Outubro</option>
                        <option value="11">Novembro</option>
                        <option value="12">Dezembro</option>
                    </select>
                    
                    <input type="submit" name="submit" class="submit" value="PESQUISAR">
                </form>
            </div>
        </div>
    </div><!--eng_background_int-->

</div><!--content-->