<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>INFORMATIVOS</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Informativos
        </div>
    </div>
    <div class="eng_background_int">
        <div class="informativo_int">
            <div class="item_informativo">
                <div class="img_informativo">
                    <a href="../informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html" title="Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG"><img src="../wp-content/uploads/2015/01/DSC_6054-174x103.jpg" alt="Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG"/></a>
                </div>
                <div class="info_informativo">
                    <span style="font-size:11px;">22 de janeiro de 2015 - 12:02</span>
                    <h5><a href="../informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html">Lançamento do XXIV Rodeio é Hoje as 20:00hs no Galpão do CTG</a></h5>
                    <p><a href="../informativo/lancamento-do-xxiv-rodeio-e-hoje-as-2000hs-no-galpao-do-ctg/index.html">Hoje é o grande dia do Lançamento do XXIV Rodeio Crioulo Interestadual do CTG Espelho da Tradição.</a></p>
                </div>
            </div>
        </div>
        <div class="posts_pagination">
            <div class='wp-pagenavi'>
                <span class='current'>1</span><a class="page larger" href="page/2/index.html">2</a><a class="nextpostslink" rel="next" href="page/2/index.html">»</a>
            </div>    
        </div>
    </div>
</div>