<div class="content">
    <div class="title_breadcrumb">
        <div class="title_int">
            <h2>INFORMATIVOS</h2>
        </div>
        <div class="breadcrumb">
            <a href="/site">Página inicial</a> &raquo; Informativos
        </div>
    </div>
    <div class="eng_background_int">
        <div class="informativo_int">
           
            <?php foreach ($informativos as $item): ?>
            <div class="item_informativo">
                <div class="img_informativo">
                    <a href="" title=""><img src="" alt=""/></a>
                </div>
                <div class="info_informativo">
                    <span style="font-size:11px;"><?php  ?></span>
                    <h5><a href=""><?php  ?></a></h5>
                    <p><a href="<?php  ?>"> <?php  ?> </a></p>
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
        
        <div class="posts_pagination">
            <div class='wp-pagenavi'>
                <span class='current'>1</span><a class="page larger" href="page/2/index.html">2</a><a class="nextpostslink" rel="next" href="page/2/index.html">»</a>
            </div>    
        </div>
        
    </div>
</div>