<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Admin ' . $this->translate(' - CTG POTRO SEM DONO'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap-filestyle.js'))
        ;
        ?>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
