<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Admin ' . $this->translate(' - CTG POTRO SEM DONO'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
                ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
                ->prependStylesheet($this->basePath('css/admin.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
        ?>
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('plugins/jquery.validate.js'))
                ->prependFile($this->basePath('plugins/jquery.plainoverlay.js'))
                ->prependFile($this->basePath('js/main.js'))
                ->prependFile($this->basePath('dist/js/app.min.js'))
                ->prependFile($this->basePath('dist/js/demo.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
    </head>
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">
            <header class="main-header">
                <a href="/admin" class="logo">
                    <span class="logo-mini"><b>CTG</b></span>
                    <span class="logo-lg"><b>CTG</b></span>
                </a>
                <nav class="navbar navbar-static-top" role="navigation">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <section class="sidebar">
                    <ul class="sidebar-menu">
                        <li class="header">Menu de Navegação</li>
                        <li>
                            <a href="/admin">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
                            </a>
                        </li>
                        <li>
                            <a href="/admin/informativos">
                                <i class="glyphicon glyphicon-bookmark"></i>
                                <span>Informativos</span>
                            </a>
                        </li>
                        <li>
                            <a href="/admin/agenda">
                                <i class="glyphicon glyphicon-calendar"></i> <span>Agenda</span>
                            </a>
                        </li>
                        <li>
                            <a href="/admin/galeria-de-fotos">
                                <i class="glyphicon glyphicon-camera"></i>
                                <span>Galeria de Fotos</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="glyphicon glyphicon-usd"></i> <span>Financeiro</span>
                            </a>
                        </li>
                    </ul>
                </section>
            </aside>
            <div class="content-wrapper">

                <div id="messages">
                    <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                        <div class="alert alert-success">
                            <?php foreach ($this->flashMessenger()->getSuccessMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>


                    <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                        <div class="alert alert-danger">
                            <?php foreach ($this->flashMessenger()->getErrorMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>

                    <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                        <div class="alert alert-warning">
                            <?php foreach ($this->flashMessenger()->getInfoMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong ><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
                
                <?php echo $this->content; ?>
            
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0
                </div>
                <strong>Copyright &copy; 2015 - <?php echo date('Y') ?> Compuwave Tecnologia LTDA</strong>
            </footer>
        </div>
    </body>
</html>
