<div class="container">
    <div class="card card-container">
        <form class="form-signin">
            <span id="reauth-email" class="reauth-email"></span>
            <input type="email" id="inputEmail" class="form-control" placeholder="E-mail" required autofocus>
            <button class="btn btn-lg btn-success btn-block btn-signin" type="submit">Recuperar</button>
        </form>
    </div>
</div>