<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Potro Sem Dono ' . $this->translate(' - Admin - Desenvolvido Por Compuwave Tecnologia'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
                ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
                ->prependStylesheet($this->basePath('css/main.css'))
        ?>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('plugins/jquery.validate.js'))
                ->prependFile($this->basePath('plugins/jquery.plainoverlay.js'))
                ->prependFile($this->basePath('js/main.js'))
                ->prependFile($this->basePath('dist/js/app.min.js'))
                ->prependFile($this->basePath('dist/js/demo.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">
            <header class="main-header">
                <a href="/main" class="logo">
                    <span class="logo-mini"><b>CTG</b></span>
                    <span class="logo-lg"><b>CTG</b></span>
                </a>
                <nav class="navbar navbar-static-top" role="navigation">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <section class="sidebar">
                    <ul class="sidebar-menu">
                        <li class="header">Menu de Navegação</li>
                        <li>
                            <a href="/main">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
                            </a>
                        </li>
                        <li>
                            <a href="/main/integracoes">
                                <i class="fa fa-briefcase"></i>
                                <span>Integrações</span>
                            </a>
                        </li>
                        <li>
                            <a href="/main/produtos">
                                <i class="fa fa-dropbox"></i> <span>Produtos</span>
                            </a>
                        </li>
                        <li>
                            <a href="/main/pedidos">
                                <i class="fa fa-list-ol"></i>
                                <span>Pedidos</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-refresh"></i>
                                <span>Sincronizações</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="">
                                <i class="fa fa-file-pdf-o"></i> <span>Relatórios</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="glyphicon glyphicon-usd"></i> <span>Financeiro</span>
                            </a>
                        </li>
                        <li>
                            <a href="/main/config">
                                <i class="fa fa-wrench"></i> <span>Configurações</span>
                            </a>
                        </li>
                    </ul>
                </section>
            </aside>
            <div class="content-wrapper">
                <?php echo $this->content; ?>
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0
                </div>
                <strong>Copyright &copy; 2015 - <?php echo date('Y') ?> Compuwave Tecnologia LTDA</strong>
            </footer>
        </div>
    </body>
</html>
